name: Lotto Bot

on:
  schedule:
    - cron: '0 9 * * *' # 매일 오후 6시쯤(태국시간) 실행
  workflow_dispatch: # 수동 실행 버튼

permissions:
  contents: write # 글쓰기 권한

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - run: python main.py
      - run: |
          git config --global user.name 'LottoBot'
          git config --global user.email 'bot@noreply.github.com'
          git add index.html
          git commit -m "Update lotto result" || echo "No changes"
          git push
