name: Lottery Update Bot

on:
  schedule:
    - cron: '0 9 * * *' # 매일 실행 (태국시간 오후 4시쯤)
  workflow_dispatch: # 수동 실행 버튼

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install libraries
        run: pip install requests

      - name: Run script
        run: python main.py

      - name: Commit and Push
        run: |
          git config --global user.name 'LottoBot'
          git config --global user.email 'bot@noreply.github.com'
          git add index.html
          git commit -m "Update lottery data" || echo "No changes"
          git push
